---
title: "Cleaning"
---
# Preparing the information
## Loading the libraries
```{r include=FALSE}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(janitor)
```

```{r load the global meat production data set, include=FALSE}
production_df <- data.frame(read_csv("archive (5)/global-meat-production.csv"))
```

```{r}
#Formatted the columns titles to lowercase
production_df <- clean_names(production_df)
```

```{r}
#Used the pipe operator to rename the columns
production_df <- production_df %>% 
  rename(country = entity,
         country_code = code,
         production = `livestock_primary_meat_total_1765_production_5510_tonnes_tonnes`)
```

```{r}
#filtered OWID_WRL 
#created new data frame
country_code_world <- filter(production_df, country_code == "OWID_WRL")
```

```{r}
continents <- filter(production_df,is.na(country_code))
```

```{r}
v2_productiondf <- production_df
```

```{r}
v2_productiondf <- v2_productiondf %>% 
  filter(!is.na(country_code))
```

```{r}
v2_productiondf <- v2_productiondf %>% 
  filter(country_code != "OWID_WRL")
```

```{r}
countries <- unique(v2_productiondf[c("country")])
```

```{r}
years <- unique(v2_productiondf[c("year")])
```
#JA coding ends

# Loading data information from CVS (consumption)
```{r load the global meat consumption data set, include=FALSE}
pc_meat_consumption_kg <- read_csv("docs/archive (5)/per-capita-meat-consumption-by-type-kilograms-per-year.csv")
```

## Pipe to clean the data information of consumption by country
```{r rename columns, filter out continents and change na values for na1}
#Used the pipe operator to clean the names of the columns, rename columns, to filter na codes (df without continents) and change the na values to 0.
pc_meat_consumption_kg_country <- pc_meat_consumption_kg %>%
  clean_names() %>%
  rename(mutton_goat_kg = mutton_and_goat_kilograms_per_year,
         other_kg = other_meats_kilograms_per_person,
         poultry_kg = poultry_kilograms_per_year,
         pigmeat_kg = pigmeat_kilograms_per_year,
         beef_bufallo_kg = beef_and_bufallo_kilograms_per_year) %>%
  filter(!is.na(code)) %>% 
  mutate_all( ~replace(., is.na(.), 0.0))
```
## Pipe to clean the data information of consumption by continent
```{r rename columns, filter out continents and change na values for na}
#Used the pipe operator to clean the names of the columns, rename columns, to filter na codes (df without continents) and change the na values to 0.
pc_meat_consumption_kg_continent <- pc_meat_consumption_kg %>%
  clean_names() %>%
  rename(mutton_goat_kg = mutton_and_goat_kilograms_per_year,
         other_kg = other_meats_kilograms_per_person,
         poultry_kg = poultry_kilograms_per_year,
         pigmeat_kg = pigmeat_kilograms_per_year,
         beef_bufallo_kg = beef_and_bufallo_kilograms_per_year) %>%
  filter(is.na(code))
```

#JA begins 8/4/21
```{r}
countries <- unique(v2_productiondf[c("country")])
years <- unique(v2_productiondf[c("year")])
```

```{r}
#Grouped the countries and sum the production
p_countries <- v2_productiondf %>%
  select(c(country, production)) %>%
  group_by(country)%>%
  summarise(production = sum(production)) %>% 
  arrange(desc(production))
```

```{r}
#5 Top Countries produces meat.
p_countries %>% 
  select(country,production) %>% 
  head(n=5)
```
```{r}
#5 Bottom Countries produces meat. 
p_countries %>% 
  select(country, production) %>% 
  tail(n=5)
```
```{r}
#Graph showing the lowest countries producing meat from 1960-2018
p_countries %>% 
  select(country, production) %>% 
  arrange(production) %>% 
  head(n=5) %>% 
  ggplot(aes(x=country, y=production, fill=production))+ 
  geom_col()+
  theme(axis.text.x = element_text(angle = 50, hjust=1))+
  labs(y="Production", x= "Country",title="Bottom Countries - Global Meat Production", subtitle ="between 1960 to 2018")
```
```{r}
#Graph showing the top countries producing meat from 1960-2018
p_countries %>% 
  select(country,production) %>% 
  head(n=5) %>%
  mutate(production = production / 1000000) %>%
  ggplot(aes(x=country, y=production, fill=production))+
  geom_col() + 
  labs(y="Production in Mio.", x= "Country",title="Top Countries - Global Meat Production", subtitle ="between 1960 to 2018") 
```
```{r}
#Summary that presents the top countries that produces meat in 1961.
v2_productiondf %>% 
  select(country, year, production) %>%
  filter(year == 1961) %>%
  arrange(desc(production)) 
```
```{r}
#Boxplot presents the top countries that produces meat in 1961.
v2_productiondf %>% 
  select(country, year, production) %>%
  filter(year == 1961) %>%
  arrange(desc(production)) %>%
  head(n=10) %>%
  ggplot(aes(x = country,y=production/1000000)) + 
  geom_boxplot()+
  stat_summary(fun=mean, geom="point", shape=23, size=4)+
  theme(axis.text.x = element_text(angle = 50, hjust=1))+
  labs(y="Production", x= "Country",title="Global Meat Production", subtitle ="Top Countries in 1961")
```
```{r}
#Summary that presents the top countries that produces meat in 2018.
v2_productiondf %>% 
  select(country, year, production) %>%
  filter(year == 2018) %>%
  arrange(desc(production)) 
```
```{r}
#Boxplot presents the top countries that produces meat in 2018.
v2_productiondf %>% 
  select(country, year, production) %>%
  filter(year == 2018) %>%
  arrange(desc(production)) %>%  
  head(n=10) %>% 
  ggplot(aes(x = country, y=production/1000000)) +
  geom_boxplot()+
  stat_summary(fun=mean, geom="point", shape=23, size=4)+
    theme(axis.text.x = element_text(angle = 50, hjust=1))+
  labs(y="Production", x= "Country",title="Global Meat Production", subtitle ="Top Countries in 2018")
```
```{r}
#Summary that presents the lowest countries that produces meat in 1961.
v2_productiondf %>% 
  select(country, year, production) %>%
  filter(year == 1961) %>%
  arrange(production) 
```
```{r}
#Boxplot presents the lowest countries that produces meat in 1961.
v2_productiondf %>% 
  select(country, year, production) %>%
  filter(year == 1961) %>%
  arrange(production) %>% 
  head(n=10) %>% 
ggplot(aes(x = country, y=production)) + 
  geom_boxplot()+
  stat_summary(fun=mean, geom="point", shape=23, size=4)+
    theme(axis.text.x = element_text(angle = 50, hjust=1))+
    labs(y="Production", x= "Country",title=" Global Meat Production", subtitle ="Bottom Countries in 1961")
```
```{r}
#Summary that presents the lowest countries that produces meat in 2018.
v2_productiondf %>% 
  select(country, year, production) %>%
  filter(year == 2018) %>%
  arrange(production) 
```
```{r}
#Boxplot presents the lowest countries that produces meat in 2018.
v2_productiondf %>% 
  select(country, year, production) %>%
  filter(year == 2018) %>%
  arrange(production) %>% 
  head(n=10) %>% 
ggplot(aes(x = country, y=production)) + 
  geom_boxplot()+
  stat_summary(fun=mean, geom="point", shape=23, size=4)+
    theme(axis.text.x = element_text(angle = 50, hjust=1))+
    labs(y="Production", x= "Country",title="Total Global Meat Production", subtitle ="Bottom Countries in the 2018")
```
```{r}
#Line graph illustrating global total amount of meat produced from 1960-2018. 
v2_productiondf %>% 
    group_by(year) %>% 
    summarise(production = sum(production)) %>% 
    ggplot(aes(x=year,y=production/1000000))+
    geom_line(colour="red")+
    theme_classic()+
    scale_x_continuous(breaks = round(seq(min(v2_productiondf$year), max(v2_productiondf$year), by = 5)))
labs(y="Production", x= "Year",title="Total Global Meat Production", subtitle ="between 1960 to 2018")
```
```{r}
#Line graph illustrating global total amount of meat produced from 2008-2018.
v2_productiondf %>% 
    group_by(year) %>% 
    summarise(production = sum(production)) %>%
    arrange(desc(production)) %>% 
    head(n=10) %>% 
    ggplot(aes(x=year, y=production))+
    geom_line(colour="red")+
    labs(y="Production", x= "Year",title="Total Global Meat Production", subtitle ="between 2008 to 2018")
```
```{r}
#Line graph illustrating global total amount of meat produced from 1960-1970.
v2_productiondf %>% 
    group_by(year) %>% 
    summarise(production = sum(production)) %>%
    arrange((production)) %>% 
    head(n=10) %>% 
    ggplot(aes(x=year, y=production))+
    geom_line(colour="orange")+
    theme_gray()+
  labs(y="Production", x= "Year",title="Total Global Meat Production", subtitle ="between 1960 to 1970")
```
```{r}
#Line graph showing China as one of the top countries that mass produces meat from 1960-2018.
v2_productiondf %>% 
  filter(country == "China") %>% 
  select(country,year,production) %>%
  ggplot(aes(x=year, y=production/100000))+
  geom_line(colour="white")+
  theme_dark()+
  labs(y="Production", x= "Year",title="Global Meat Production per Year from China", subtitle ="between 1960 to 2018")
```
```{r}
#Line graph showing Bermuda as one of the bottom countries that mass produces meat from 1960-2018.
v2_productiondf %>% 
  filter(country == "Bermuda") %>% 
  select(country,year,production) %>%
  ggplot(aes(x=year, y=production,fill=year ))+
  geom_line(colour="blue")+
  theme_dark()+
  labs(y="Production", x= "Year",title="Global Meat Production per Year from Bermuda", subtitle ="between 1960 to 2018")
```